name: codylab-talent-be-2025

services:
  codylab-postgresql:
    image: postgres:15.3
    container_name: codylab-postgresql
    environment:
      - POSTGRES_DB=projects_management
      - POSTGRES_USER=codylab
      - POSTGRES_PASSWORD=cody|_ab2025
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U codylab -d projects_management' ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    networks:
      - gaetano-pensaci-tu

  codylab-keycloak:
    build:
      context: .
      dockerfile: Dockerfile-keycloak
    container_name: codylab-keycloak
    command:
      - start-dev
      - --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_PORT=9090
      - KC_HTTPS_PORT=9443
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://codylab-postgresql:5432/projects_management
      - KC_DB_USERNAME=codylab
      - KC_DB_PASSWORD=cody|_ab2025
    depends_on:
      codylab-postgresql:
        condition: service_healthy
    ports:
      - "9090:9090"
      - "9443:9443"
    networks:
      - gaetano-pensaci-tu

  codylab-2025-api:
    image: intesys/codylab-2025:main
    container_name: codylab-2025-api
    depends_on:
      codylab-postgresql:
        condition: service_healthy
      codylab-keycloak:
        condition: service_started
    environment:
      - CODYLAB_DATASOURCE_URL=jdbc:postgresql://codylab-postgresql:5432/projects_management
      - CODYLAB_DATASOURCE_USERNAME=codylab
      - CODYLAB_DATASOURCE_PASSWORD=cody|_ab2025
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8090
      - MANAGEMENT_SERVER_PORT=8081
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://codylab-keycloak:9090/realms/codylab
    ports:
      - "8090:8090"
      - "8081:8081"
    networks:
      - gaetano-pensaci-tu

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - codylab-2025-api
    networks:
      - gaetano-pensaci-tu

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=suadmarianetflix2025@gmail.com
      - GF_SMTP_PASSWORD=Maria2025!!!
      - GF_SMTP_FROM_ADDRESS=suadmarianetflix2025@gmail.com
      - GF_SMTP_FROM_NAME=Grafana
      - GF_SMTP_SKIP_VERIFY=false
    depends_on:
      - prometheus
    networks:
      - gaetano-pensaci-tu

volumes:
  postgres_data:

networks:
  gaetano-pensaci-tu:
    driver: bridge
