spring:
  application:
    name: codylab-2025

  profiles:
    active: local

server:
  port: 8090

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    disable-swagger-default-url: false
    path: /swagger-ui.html
