spring:
  application:
    name: codylab-2025

codylab:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestione_progetti
    username: codylab
    password: cody|_ab2025
    driver: org.postgresql.Driver

  logging:
    level:
      root: info


server:
  port: 8090