spring:
  application:
    name: codylab-2025

  profiles:
    active: local

server:
  port: 8090

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health, info, livenessstate, readinessstate, prometheus
  endpoint:
    health:
      show-details: always
