version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: codylab
      POSTGRES_PASSWORD: cody|_ab2025
      POSTGRES_DB: formegeometriche
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zipkin:
      image: openzipkin/zipkin:3.5.1
      container_name: zipkin
      restart: always
      env_file:
        - .env
      ports:
        - "9411:9411"
      environment:
        - STORAGE_TYPE=mem

volumes:
  postgres_data: